Store tupperware data
cook4me/android pull request #152
Opened 2023-04-26 17:07 UTC by bu-da

This PR stores the tupperware data received via form in Firebase store and Firebase Cloud Storage (images). It adds the Cancel Button functionality.

2023-04-26 21:57 UTC, nino-gerb approved these changes
Overall it looks really nice. Thank you so much for the storage of the Images. I can really use it! It would be nice to have a closer look at the tupperwareform function together.

2023-04-26 21:57 UTC, nino-gerb commented on storage.rules
> +  match /b/{bucket}/o {
Maybe we should consider security once

2023-04-26 21:57 UTC, nino-gerb commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/tupperwareform/CreateTupperwareScreen.kt
> +        remember { RequiredTextFieldState(context.getString(R.string.TupCreateBlank)) }
Could you please explain to me why remember is needed?

2023-04-26 21:57 UTC, nino-gerb commented on app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/TupperwareRepository.kt
> +                storageRef.child("/images/$email/$title/${UUID.randomUUID()}")
Would it make more sense to use the userID as first repository?

2023-04-26 22:03 UTC, JohnTomasTaylor requested changes
The code is clean! Thanks for the hard work. 
There's just one thing bugging me about the tupperware creation test, I feel like it might be adding a tupperware to the real firebase database as it is using an unmocked recipeRepository. Could you maybe the check firebase console as I don't have access to it...

2023-04-27 07:07 UTC, bu-da commented on firebase.json
>    }
This are the security rules for the firebase emulator and not the real cloud storage. But it would be probably a good idea to mirror the security rules we have there. At the moment, they are the same and they are the least restrictive they can be (everybody can write/read). We definitely should restrict this in the future so that only authenticated users can do this. I created an issue for this (we might need to adapt some tests and so it maybe takes some time): https://github.com/cook4me/android/issues/153

2023-04-27 07:08 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/tupperwareform/CreateTupperwareScreen.kt
>          )
At the moment, I can only can think about over-engineered solutions, but maybe you can draft something?

2023-04-27 07:52 UTC, bu-da commented on app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/tupperwareform/TupperwareCreationScenarioTest.kt
>              }
Very good point! Thanks for pointing it out! It seems not to, but due to time constraints I didn't investigate it any further. I adapted the test according to your suggestion.

2023-04-27 07:54 UTC, bu-da commented on storage.rules
> +  match /b/{bucket}/o {
Very good point, I created an issue for this: https://github.com/cook4me/android/issues/153

2023-04-27 08:26 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/TupperwareRepository.kt
> +                storageRef.child("/images/$email/$title/${UUID.randomUUID()}")
Maybe it does. We should sit together and discuss the general structure (but not as part of this pull request). Maybe sth like this?
> userId
   \ profile
   \ tupperware
      \title1
      \title2
      \title3

2023-04-27 08:27 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/tupperwareform/CreateTupperwareScreen.kt
> +                    repository.add(title, description, images)
we definitely can improve the robustness, but I would like to this later.

2023-04-27 13:56 UTC, merged