Refactor/chat
cook4me/android pull request #282
Opened 2023-05-20 12:51 UTC by Tachi-67

- I disabled the header (the channel list name, the pencil, the avatar) becuase they are kind of misleading.
- I enabled the action of long click on channel -> view channel info -> jump to the profile of the user chatting with.
- I keep record of user email in the chat user's extra data upon clicking inside of the chat feature.
- TODO: find a way to somehow pass the profile picture to the chat user

2023-05-22 12:56 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/BottomNavigationBar.kt
> +    BottomNavScreen.Chat,
Nitpick: Comma could be removed

2023-05-22 16:19 UTC, bu-da requested changes
Thanks a lot for your work :-). I pulled your branch and there are a few things that needs to be addressed, before we're finally done with the chat:
* When I'm switching back and forth between the features, the chat is unsuable pretty fast. First it's shown that I'm disconnected in the Chat Header instead of the channel name. When I switch to another feature and back our loading screen is shown constantly. The chat feature is not really usable like this :-( How can we fix this?  
* If I use the search and type e.g. "2023" the channel "sdp2023cook4me" doesn't appear. Do you have control over this?
* If I click on the header in the chat I land on the profile, which is good. Didn't we say we want to see the navigation bar then? Or it would be good to have at least a back button or sth
* The loading screen of the chat is still shown. It doesn't look good if we have two loading screens.  I see two options:
      - overwrite somehow the `loadingContent` parameter of the [`ChannelList` composable](https://getstream.io/chat/docs/sdk/android/compose/channel-components/channel-list/#customization)
      - use their loading screen instead of ours in the whole app
* There aren't any tests
* Question: Can we apply our colors / design to the screens?
Other issue: I still don't like that we have multiple Activities now, but as long as it is functional this is not a priority.

2023-05-22 16:19 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/MessagesActivity.kt
> +                        if (targetEmail != null) {
Nitpick: You could the following instead:
```
targetEmail?.let {...}
```

2023-05-22 16:19 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/MessagesActivity.kt
> +                        val targetMember = channel.members.find { it.user.extraData["email"] != userEmail }
Nitpick: You're already using constants, which is good! The string `"email"` could also be one

2023-05-22 16:19 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChannelScreen.kt
> +                        val targetMember = channel.members.find { it.user.extraData["email"] != userEmail }
Nitpick: getting the targetEmail seems to be same logic in this composable and in the MessagesActivity. Can you create a helper for it?

2023-05-22 16:19 UTC, bu-da commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChannelScreen.kt
> -    }
Question: We don't need this anymore?

2023-05-23 11:53 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChannelScreen.kt
> -    }
no, I tried to move the disconnect into a queue (like you suggested) and it turned out this call never succeeds

2023-05-23 11:54 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/Cook4MeApp.kt
> +    val screensWithBottomBar = mainDestinations.map { it.route } + Screen.ProfileScreen.name
This is to show button nav bar also in the user's own profile screen.

2023-05-23 12:01 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ImageLoaderDecorator.kt
> +const val PROFILE_IMAGE_PREFIX = "load profile image"
done

2023-05-23 12:04 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
> +            val userId = backStackEntry.arguments?.getString("userId")
done

2023-05-23 12:32 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/MessagesActivity.kt
> +                        if (targetEmail != null) {
done

2023-05-23 12:34 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/MessagesActivity.kt
> +                        val targetMember = channel.members.find { it.user.extraData["email"] != userEmail }
might be a good idea to leave indexes as clear text for readability

2023-05-23 19:02 UTC, bu-da approved these changes
I still don't like that we can't avoid the connection timeouts, but we at least inform the users about it. Thanks for adding the dialog and clarifying my questions in your comment and today at the meeting

2023-05-23 20:29 UTC, merged