Feature/beautify recipefeed
cook4me/android pull request #304
Opened 2023-05-23 11:41 UTC by JohnTomasTaylor

This pull request combines two pull requests so merging is easier:
- adds the challenge feed that enables searching and filtering through challenges
- updates the UI for the recipe item in the recipe feed

2023-05-23 18:24 UTC, Tachi-67 requested changes
Thank you for the biiiiiiiig pr!!!! The code is super nice and clear.

I picked a few spots for improvements, among them I think the most important is not to call `runBlocking` in tests, but use `runTests`.

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeItemTest.kt
> +        composeTestRule.onNodeWithText("JOINED").assertExists()
Might be a good idea to use `....performScrollTo()` and then `....assertIsPerformed()`, as `assertExists()` doesn't really check if the component is displayed on the screen.

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipe/RecipeCreationScenarioTest.kt
>              runBlocking {
Please do not use runBlocking, but use runTest() when declaring the test function, and add `@ExperimentalCoroutinesApi` annotation.

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/details/ChallengeDetailedViewModel.kt
> +        Log.d("Debug", "challengeId = $challengeId")
Please remove the debug sentences when merging.

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeFeedScreen.kt
> +        Log.d("Challenge", "Load new data")
Please remove debug sentences when merging

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeFeedScreen.kt
> +    val currentUser = AccountService().getCurrentUser()
might be a good idea to inject the accountService to the screen, instead of decalring something here, this will ease for tests.

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/FilterScreen.kt
> +        title = { Text(text = "Filter") },
Could move cleartexts to the string.xml file

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/SeachBar.kt
> +                            text = "Search...",
Could move cleartexts to the string.xml file

2023-05-23 18:24 UTC, Tachi-67 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/form/CreateChallengeScreen.kt
>                      endMsg.value = challengeFormService.submitForm(challenge.value) ?: "Challenge created!"
Cleartexts again ;-)

2023-05-24 08:02 UTC, JohnTomasTaylor commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/details/ChallengeDetailedViewModel.kt
> +        Log.d("Debug", "challengeId = $challengeId")
I'll do that

2023-05-24 08:03 UTC, JohnTomasTaylor commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeFeedScreen.kt
> +    val currentUser = AccountService().getCurrentUser()
Yes I completely agree

2023-05-24 08:42 UTC, Tachi-67 approved these changes
thanks for the changes, lgtm now ;-)

2023-05-24 08:58 UTC, merged