Feature/recipe form
cook4me/android pull request #83
Opened 2023-03-29 19:03 UTC by JohnTomasTaylor

Finally... 
Added a basic UI (with drop-down menus and textfields that format input as a list (ex: bulletpoints, enumerated lists)) for recipe creation

2023-03-30 19:41 UTC, dayan9265 requested changes
The code looks good and lots of work done, well done! Maybe for a next time, it would be a good idea to do multiple PR on smaller objects to avoid a too big PR ^^. I left some comments to review, some simple and other some ideas for future refactoring (that could be done an another time)

2023-03-30 19:41 UTC, dayan9265 commented on app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipeform/RecipeCreationScenarioTest.kt
> +        composeTestRule.onNodeWithContentDescription(getString(R.string.RecipeNameTextFieldDesc))
what is the goal of this line (it repeats afterwards)? It seems you find the node and then test/perform nothing on it

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/MainActivity.kt
It is good for debugging to go directly to your part, but you should not let it on the final version

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/application/RecipeService.kt
> +        photos: List<String>,
I guess the photos are currently `List<String>` to test the implementation, but it will change later or will it stay and if yes what does these strings represents?

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/persistence/model/Recipe.kt
Is there a reason why the cooking time is a `string` (and not for example, two `int` for _minute_ and _hour_ for example?

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/common/form/BulletPointTextField.kt
Idea: shouldn't the "logic" be in an another file (i.e the object `GenericSeparators` and the class `ListVisualTransformation`) and keep only the `@composable` here?

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/common/form/CustomDropDownMenu.kt
> +                // trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) },
comment could be removed

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/common/form/CustomTextField.kt
> +    val stateDescription = if (isError) { "Error" } else { "" }
nitpick: "error" should be stored in the string resource

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/common/form/FormState.kt
maybe add some comments, because I am not completely sure what this is supposed to do

2023-03-30 19:41 UTC, dayan9265 commented on app/src/main/java/ch/epfl/sdp/cook4me/ui/recipeform/CreateRecipeScreen.kt
maybe try to create multiple files for the composable function, because it begins to be a big file, with lots of `@composable` elements

2023-03-30 22:06 UTC, dayan9265 approved these changes

2023-03-31 10:23 UTC, bu-da commented
Due to time constraints we merge this pull request and the feedback will be tackled in the next sprint: https://github.com/cook4me/android/pull/83

2023-03-31 10:28 UTC, merged